# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Pull docker image
        run: docker pull microros/micro_ros_static_library_builder:iron

      # Runs a set of commands using the runners shell
      - name: Build project
        run: |
          echo $(pwd)
          chmod 777 $(pwd)/micro_ros_stm32cubemx_utils/microros_static_library/library_generation/library_generation.sh
          chmod u+x $(pwd)/micro_ros_stm32cubemx_utils/microros_static_library/library_generation/library_generation.sh
          docker run --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=micro_ros_stm32cubemx_utils/microros_static_library microros/micro_ros_static_library_builder:iron
      
      - name: Pack library
        run: tar -zcvf micro_ros_stm32cubemx_utils_build.tar.gz micro_ros_stm32cubemx_utils

      - uses: ncipollo/release-action@v1
        with:
          tag: "AutoBuild"
          prerelease: true
          allowUpdates: true
          artifacts: "micro_ros_stm32cubemx_utils_build.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
